# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
print(s.split())

['Hi', 'there', 'Sam!']

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print("The diameter of", planet ,"is", diameter ,"kilometers.")

The diameter of Earth is 12742 kilometers.

## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [8]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello

# Numpy

In [11]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [12]:
array=np.zeros(10)

In [13]:
array=np.ones(10)*5

## 5. Create an array of all the even integers from 20 to 35

In [14]:
import numpy as np
array=np.arange(20,35,2)

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [26]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a,b
print(c)

(array([1, 2, 3]), array([4, 5, 6]))

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [27]:
import pandas as pd

In [39]:
data = [['Akash',6001],['Praveen Raj',6018],['Viswanath',6304],['Harish',6007]]
df = pd.DataFrame(data,columns=['Name','Reg'])
print(df)

          Name   Reg
0        Akash  6001
1  Praveen Raj  6018
2    Viswanath  6304
3       Harish  6007

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [35]:
dates = pd.date_range(start = '1-1-2023',end = '2-10-2023')
print(dates)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [36]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [37]:
df = pd.DataFrame.from_records(lists)
print(df)

   0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24